<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T01_sekolah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T01_sekolah_model');
        $this->load->library('form_validation');
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t01_sekolah/t01_sekolah_list');
        $data['_view'] = 't01_sekolah/t01_sekolah_list';
        $this->load->view('dashboard/dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T01_sekolah_model->json();
    }

    public function read($id)
    {
        $row = $this->T01_sekolah_model->get_by_id($id);
        if ($row) {
            $data = array(
				'id' => $row->id,
				'nama' => $row->nama,
				'alamat' => $row->alamat,
			);
            $this->load->view('t01_sekolah/t01_sekolah_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_sekolah'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('t01_sekolah/create_action'),
			'id' => set_value('id'),
			'nama' => set_value('nama'),
			'alamat' => set_value('alamat'),
		);
        $this->load->view('t01_sekolah/t01_sekolah_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'nama' => $this->input->post('nama',TRUE),
				'alamat' => $this->input->post('alamat',TRUE),
			);

            $this->T01_sekolah_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t01_sekolah'));
        }
    }

    public function update($id)
    {
        $row = $this->T01_sekolah_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('t01_sekolah/update_action'),
				'id' => set_value('id', $row->id),
				'nama' => set_value('nama', $row->nama),
				'alamat' => set_value('alamat', $row->alamat),
			);
            $this->load->view('t01_sekolah/t01_sekolah_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_sekolah'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
				'nama' => $this->input->post('nama',TRUE),
				'alamat' => $this->input->post('alamat',TRUE),
			);

            $this->T01_sekolah_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t01_sekolah'));
        }
    }

    public function delete($id)
    {
        $row = $this->T01_sekolah_model->get_by_id($id);

        if ($row) {
            $this->T01_sekolah_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t01_sekolah'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_sekolah'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('nama', 'nama', 'trim|required');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T01_sekolah.php */
/* Location: ./application/controllers/T01_sekolah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-30 16:36:12 */
/* http://harviacode.com */